[pytest]
pythonpath =
    phase14/src
    phase13/src
    phase12/src
    phase11/src
    phase10/src
    phase9/src
    phase8/src
    phase7/src
    phase6/src
    phase5/src
    phase4/src
    phase3/src
    phase2/src
    phase1/src
    phase0/src
    .
norecursedirs =
    .*
    build
    dist
    CVS
    _darcs
    {arch}
    *.egg
    fixtures
    .worktrees
