---
- name: Restart systemd-journald
  ansible.builtin.systemd:
    name: systemd-journald.service
    state: restarted
  when:
    - base_os_mutating_operations_enabled | bool
    - base_os_manage_journald_service | bool

- name: Apply update-grub configuration update
  listen: Apply grub configuration update
  ansible.builtin.command:
    argv: "{{ base_os_update_grub_command }}"
  changed_when: false
  when:
    - base_os_update_grub_manage_runtime | bool
    - not ansible_check_mode
