---
- name: Restart systemd-journald
  ansible.builtin.systemd:
    name: systemd-journald.service
    state: restarted
  when: base_os_mutating_operations_enabled | bool

- name: Apply grub configuration update
  ansible.builtin.command:
    argv:
      - /usr/sbin/update-grub
  changed_when: false
  when:
    - base_os_mutating_operations_enabled | bool
    - not ansible_check_mode
