---
networking_manage_netplan: false
networking_apply: false
networking_allow_ssh_disruption: false
networking_root_dir: /
networking_netplan_file: >-
  {{
    networking_root_dir ~ '/etc/netplan/60-aihost.yaml'
    if networking_root_dir != '/'
    else '/etc/netplan/60-aihost.yaml'
  }}
networking_renderer: networkd
networking_ethernets: {}
networking_manage_runtime: "{{ not (baseline_localhost_safe_mode | default(false) | bool) }}"
