---
all:
  children:
    ai_hosts:
      children:
        production: {}
        inference: {}
        gpu: {}
        cluster: {}
        monitoring: {}
    production:
      hosts:
        ai-p620-01: {}
        ai-5820-01: {}
    inference:
      hosts:
        ai-p620-01: {}
        ai-5820-01: {}
    gpu:
      hosts:
        ai-p620-01: {}
        ai-5820-01: {}
    cluster:
      hosts:
        ai-p620-01: {}
        ai-5820-01: {}
    monitoring:
      hosts:
        ai-p620-01: {}
        ai-5820-01: {}
