---
all:
  children:
    production:
      hosts:
        ai-p620-01: {}
    inference:
      hosts:
        ai-p620-01: {}
    gpu:
      hosts:
        ai-p620-01: {}
    monitoring:
      hosts:
        ai-p620-01: {}
