"""Containment and Authority Boundary Enforcement for Heterogeneous Orchestration.

Guarantees that all outputs generated by bounded specialists (e.g. 7B models)
are quarantined, validated out-of-process, and sanitized before any consumption
by downstream agents, tool executors, or integration pipelines.
"""

from dataclasses import dataclass, field
from enum import Enum
import re
from typing import Any, Dict, List, Optional, Tuple


class ContainmentStatus(str, Enum):
    CLEAN = "CLEAN"
    QUARANTINED = "QUARANTINED"
    REJECTED = "REJECTED"


class ThreatVector(str, Enum):
    TOOL_ESCALATION = "TOOL_ESCALATION"
    OUT_OF_SCOPE_ACCESS = "OUT_OF_SCOPE_ACCESS"
    VALIDATOR_BYPASS = "VALIDATOR_BYPASS"
    ACCEPTANCE_CRITERIA_REWRITE = "ACCEPTANCE_CRITERIA_REWRITE"
    DOWNSTREAM_INJECTION = "DOWNSTREAM_INJECTION"
    ROUTING_ALTERATION = "ROUTING_ALTERATION"
    DUPLICATE_SIDE_EFFECTS = "DUPLICATE_SIDE_EFFECTS"
    AUDIT_SUPPRESSION = "AUDIT_SUPPRESSION"


# Pinned patterns representing adversarial escape attempts
ADVERSARIAL_PATTERNS = [
    (ThreatVector.TOOL_ESCALATION, re.compile(r"(sudo|chmod\s+\+x|docker\.sock|rm\s+-rf|eval\(|exec\()", re.I)),
    (ThreatVector.OUT_OF_SCOPE_ACCESS, re.compile(r"(\/etc\/shadow|\/root|\.\.\/|\.ssh\/id_rsa|attacker\.com|evil-exfil)", re.I)),
    (ThreatVector.VALIDATOR_BYPASS, re.compile(r"(self_asserted_test_pass|bypass_validator|skip_acceptance|force_accept)", re.I)),
    (ThreatVector.ACCEPTANCE_CRITERIA_REWRITE, re.compile(r"(ignore\s+previous\s+instructions|system\s+override|set\s+acceptance\s*=\s*true)", re.I)),
    (ThreatVector.DOWNSTREAM_INJECTION, re.compile(r"(<\/?system>|<\/?instructions>|human:\s*proceed|IMPORTANT:\s*Ignore)", re.I)),
    (ThreatVector.ROUTING_ALTERATION, re.compile(r"(set_routing|override_worker|public_model_id\s*=\s*['\"]engineering\/b0['\"])", re.I)),
    (ThreatVector.AUDIT_SUPPRESSION, re.compile(r"(suppress_log|delete_manifest|disable_audit|truncate_evidence)", re.I)),
]


@dataclass
class ContainmentEnvelope:
    task_id: str
    source_model: str
    source_role: str
    raw_content: str
    status: ContainmentStatus
    detected_threats: List[ThreatVector] = field(default_factory=list)
    sanitized_content: Optional[str] = None
    quarantine_reason: Optional[str] = None
    is_safe_for_downstream: bool = False


class ExternalAuthorityBoundary:
    """Enforces non-negotiable external authority invariants."""

    def __init__(self, permitted_tools: Optional[List[str]] = None) -> None:
        self.permitted_tools = permitted_tools or ["read_file", "run_pytest", "inspect_ast"]

    def inspect_and_quarantine(
        self,
        task_id: str,
        source_model: str,
        source_role: str,
        raw_output: str,
        channel: str = "specialist_output",
    ) -> ContainmentEnvelope:
        """Inspects raw specialist output and encloses it in a secure containment envelope."""
        detected: List[ThreatVector] = []
        reasons: List[str] = []

        # Scan against known adversarial vectors
        for vector, pattern in ADVERSARIAL_PATTERNS:
            m = pattern.search(raw_output)
            if m:
                detected.append(vector)
                reasons.append(f"Detected {vector.value} pattern '{m.group(0)}' in {channel}")

        if detected:
            return ContainmentEnvelope(
                task_id=task_id,
                source_model=source_model,
                source_role=source_role,
                raw_content=raw_output,
                status=ContainmentStatus.REJECTED,
                detected_threats=detected,
                sanitized_content=None,
                quarantine_reason="; ".join(reasons),
                is_safe_for_downstream=False,
            )

        # Quarantined sanitization: wrap in non-executable data delimiters
        sanitized = (
            f"<!-- BEGIN QUARANTINED SPECIALIST DELIVERABLE [{task_id}] -->\n"
            f"{raw_output.strip()}\n"
            f"<!-- END QUARANTINED SPECIALIST DELIVERABLE [{task_id}] -->"
        )

        return ContainmentEnvelope(
            task_id=task_id,
            source_model=source_model,
            source_role=source_role,
            raw_content=raw_output,
            status=ContainmentStatus.CLEAN,
            detected_threats=[],
            sanitized_content=sanitized,
            quarantine_reason=None,
            is_safe_for_downstream=True,
        )

    def validate_tool_dispatch(self, requested_tool: str, caller_role: str) -> bool:
        """Enforces that bounded specialists cannot authorize or execute privileged tools."""
        if caller_role != "LEAD_ENGINEERING_AUTHORITY":
            if requested_tool not in self.permitted_tools:
                raise PermissionError(
                    f"Authority Violation: Role '{caller_role}' is not authorized to invoke tool '{requested_tool}'"
                )
        return True

    def sanitize_handoff_for_lead(self, envelope: ContainmentEnvelope) -> str:
        """Prepares a specialist deliverable for inclusion in a Lead agent's prompt context."""
        if not envelope.is_safe_for_downstream:
            raise PermissionError(
                f"Handoff Denied: Deliverable from {envelope.task_id} failed containment check ({envelope.quarantine_reason})"
            )
        return envelope.sanitized_content or ""
