---
all:
  children:
    ai_hosts:
      children:
        lab: {}
        inference: {}
        gpu: {}
        cluster: {}
        monitoring: {}
      hosts:
        ai-5820-test-01:
          ansible_connection: local
          ansible_host: 127.0.0.1
          ansible_python_interpreter: /usr/bin/python3
    lab:
      hosts:
        ai-5820-test-01: {}
    inference:
      hosts:
        ai-5820-test-01: {}
    gpu:
      hosts:
        ai-5820-test-01: {}
    cluster:
      hosts:
        ai-5820-test-01: {}
    monitoring:
      hosts:
        ai-5820-test-01: {}
